FROM redis:alpine

EXPOSE 6379
# Set the default command to run when starting the container
CMD ["redis-server"]
# Set the default command to run when starting the container
# Set the default command to run when starting the container
